### ISSUE TITLE
Add forks and last push/commit date

### ISSUE THREAD

**Issue by daledude** [amanbolat/awesome-go-with-stars#1]
Nice job! Personally, I would find it even more useful with fork count and the last date code was submitted. The project updated date isn't useful to me since it includes last ticket opened even when project might be long dead. That could also be an addition though.

**Comment by amanbolat** [comment]
@daledude I have received some advice similar to yours, but since the initial idea was to create a list only with stars I should think about how do other stats fit into this repository. I might create a separate google spreadsheet with all other stats like amount of forks, issue count, diagrams etc. 

Updates will come soon!
